language: cpp

node_js:
  - "6"

os: linux

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libwebkit2gtk-4.0-dev
      - xvfb

